[default]
check-filename = true
extend-ignore-re = [
    # Ignore git commit hashes (40 character hex strings)
    "[0-9a-f]{7,40}",
]

[default.extend-identifiers]
ACI = "ACI" # Name of a connector
BA = "BA" # Bosnia and Herzegovina country code
FO = "FO" # Faroe Islands (the) country code
JOD = "JOD" # Jordan
Jod = "Jod" # Jordan
iin = "iin" # iin
PN = "PN" # Pitcairn Islands
jus = "jus" # Juspay
FPR = "FPR" # Fraud Prevention Rules

