[package]
name = "ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "connector_service_ffi"
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
# First-party dependencies
grpc-api-types = { path = "../grpc-api-types" }
connector-integration = { path = "../connector-integration" }
external-services = { path = "../external-services" }
domain_types = { path = "../domain_types" }
interfaces = { path = "../interfaces" }
cards = { path = "../cards", package = "ucs_cards" }
common_enums = { path = "../common_enums", package = "ucs_common_enums" }
common_utils = { path = "../common_utils", package = "ucs_common_utils" }
common_crate = { path = "../common_crate", package = "common_crate" }
config_patch_derive = { path = "../config_patch_derive" }
hyperswitch_masking = { git = "https://github.com/juspay/hyperswitch", tag = "2025.11.24.0", package = "masking" }

# Third-party dependencies
config = "0.14.0"
toml = "0.8"
error-stack = "0.4.1"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
serde_path_to_error = "0.1.16"
thiserror = "1.0.49"
time = { version = "0.3.36", features = ["parsing"] }
hyper = "1.6.0"
lazy_static = "1.5.0"
axum = { version = "0.8.3", features = ["macros"] }
base64 = "0.21.2"
rustc-hash = "2.0"
http = "0.2.12"
tonic = "0.13.0"
once_cell = "1.19.0"
paste = "1.0"
uuid = "1.0"
chrono = "0.4.31"
uniffi = { version = "0.28", optional = true }
napi = { version = "=2.16.0", features = ["napi4"], optional = true }
napi-derive = { version = "=2.16.0", optional = true }

[build-dependencies]
napi-build = "=2.2.0"
uniffi = { version = "0.28", features = ["build"], optional = true }

[dev-dependencies]
tempfile = "3.19.1"
hyper-util = { version = "0.1.3", features = ["tokio"] }
rand = "0.8.5"
uuid = { version = "1.0", features = ["v4"] }
reqwest = { version = "0.11", features = ["json"] }
serial_test = "3.2.0"


[features]
default = ["napi"]
napi = ["dep:napi", "dep:napi-derive"]
uniffi = ["dep:uniffi"]
c-ffi = []

[lints]
workspace = true
