name: Create hotfix branch

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create hotfix from (e.g., 2024.12.30.1)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CONNECTOR_SERVICE_CI_PAT }}

      - name: Checkout the specified tag
        shell: bash
        run: |
          git fetch --tags
          git checkout tags/${{ inputs.tag }}

      - name: Check if the input is valid tag
        shell: bash
        run: |
          TAG="${{ inputs.tag }}"
          if [[ $TAG =~ ^[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.[0-9]+$ ]]; then
            echo "::notice::$TAG is a valid CalVer tag."
          else
            echo "::error::$TAG is not a valid CalVer tag."
            exit 1
          fi

      - name: Create hotfix branch
        shell: bash
        run: |
          TAG="${{ inputs.tag }}"
          HOTFIX_BRANCH="hotfix-$TAG"

          if git switch --create "$HOTFIX_BRANCH"; then
            git push origin "$HOTFIX_BRANCH"
            echo "::notice::Created hotfix branch: $HOTFIX_BRANCH"
          else
            echo "::error::Failed to create hotfix branch"
            exit 1
          fi